spring.datasource.url=jdbc:mysql://localhost:3306/expense_management_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&useUnicode=yes&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Đổi từ update thành none để Spring Boot tôn trọng cấu hình DB gốc hiện tại của bạn, tránh xung đột cấu hình bảng
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true