spring.application.name=backend_qlct

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/ExpenseTrackerDB?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#API Key của Google Gemini
gemini.api.key=
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-lite-latest:generateContent
# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Alternatively, if you want to use SQL Server, you can uncomment these and comment the MySQL ones above:
# spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=expense_tracker;encrypt=true;trustServerCertificate=true;
# spring.datasource.username=sa
# spring.datasource.password=your_password
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
